#!/bin/bash

### ────────────────────────────────
### TEXT COLORS (FOREGROUND)
### ────────────────────────────────
BLACK      = "\e[30m";  BLK      = $BLACK
RED        = "\e[31m";  RED      = $RED
GREEN      = "\e[32m";  GRN      = $GREEN
YELLOW     = "\e[33m";  YLW      = $YELLOW
BLUE       = "\e[34m";  BLU      = $BLUE
MAGENTA    = "\e[35m";  MAG      = $MAGENTA
CYAN       = "\e[36m";  CYN      = $CYAN
GRAY       = "\e[90m";  GRY      = $GRAY
LRED       = "\e[91m";  LRD      = $LRED;      LIGHTRED      = $LRED
LGREEN     = "\e[92m";  LGRN     = $LGREEN;    LIGHTGREEN    = $LGREEN
LYELLOW    = "\e[93m";  LYLW     = $LYELLOW;   LIGHTYELLOW   = $LYELLOW
LBLUE      = "\e[94m";  LBLU     = $LBLUE;     LIGHTBLUE     = $LBLUE
LMAGENTA   = "\e[95m";  LMAG     = $LMAGENTA;  LIGHTMAGENTA  = $LMAGENTA
LCYAN      = "\e[96m";  LCYN     = $LCYAN;     LIGHTCYAN     = $LCYAN
LGRAY      = "\e[37m";  LGRY     = $LGRAY;     LIGHTGRAY     = $LGRAY
WHITE      = "\e[97m";  WHT      = $WHITE;     LIGHTWHITE    = $WHITE


### ────────────────────────────────
### BACKGROUND COLORS
### ────────────────────────────────
BACKGROUNDBLACK     = "\e[40m";   BLACKBG     = $BACKGROUNDBLACK;   BGBLK  = $BACKGROUNDBLACK
BACKGROUNDRED       = "\e[41m";   REDBG       = $BACKGROUNDRED;     BGRD   = $BACKGROUNDRED
BACKGROUNDGREEN     = "\e[42m";   GREENBG     = $BACKGROUNDGREEN;   BGGRN  = $BACKGROUNDGREEN
BACKGROUNDYELLOW    = "\e[43m";   YELLOWBG    = $BACKGROUNDYELLOW;  BGYLW  = $BACKGROUNDYELLOW
BACKGROUNDBLUE      = "\e[44m";   BLUEBG      = $BACKGROUNDBLUE;    BGBLU  = $BACKGROUNDBLUE
BACKGROUNDMAGENTA   = "\e[45m";   MAGENTABG   = $BACKGROUNDMAGENTA; BGMAG  = $BACKGROUNDMAGENTA
BACKGROUNDCYAN      = "\e[46m";   CYANBG      = $BACKGROUNDCYAN;    BGCYN  = $BACKGROUNDCYAN
BACKGROUNDSLGRAY    = "\e[47m";   LGRAYBG     = $BACKGROUNDSLGRAY;  BGLGRY = $BACKGROUNDSLGRAY
BACKGROUNDGRAY      = "\e[100m";  GRAYBG      = $BACKGROUNDGRAY;    BGGRY  = $BACKGROUNDGRAY
BACKGROUNDSLRED     = "\e[101m";  LREDBG      = $BACKGROUNDSLRED;   BGLRD  = $BACKGROUNDSLRED
BACKGROUNDSLGREEN   = "\e[102m";  LGREENBG    = $BACKGROUNDSLGREEN; BGLGN  = $BACKGROUNDSLGREEN
BACKGROUNDSLYELLOW  = "\e[103m";  LYELLOWBG   = $BACKGROUNDSLYELLOW;BGLYW  = $BACKGROUNDSLYELLOW
BACKGROUNDSLBLUE    = "\e[104m";  LBLUEBG     = $BACKGROUNDSLBLUE;  BGLBU  = $BACKGROUNDSLBLUE
BACKGROUNDSLMA      = "\e[105m";  LMAGENTABG  = $BACKGROUNDSLMA;    BGLMAG = $BACKGROUNDSLMA
BACKGROUNDSLCA      = "\e[106m";  LCYANBG     = $BACKGROUNDSLCA;    BGLCYN = $BACKGROUNDSLCA
BACKGROUNDWHITE     = "\e[107m";  WHITEBG     = $BACKGROUNDWHITE;   BGWHT  = $BACKGROUNDWHITE


### ────────────────────────────────
### FONT STYLES (PRIMARY)
### ────────────────────────────────
INVISIBLE="\e[8m";    INV=$INVISIBLE; IN=$INVISIBLE
RESETCOLOR="\e[39m";  RC=$RESETCOLOR; NC=$RESETCOLOR
RESETBG="\e[49m";     RBG=$RESETBG;   NBG=$RESETBG
RESETFONT="\e[20m";   RF=$RESETFONT;  NF=$RESETFONT
RESETALL="\e[0m";     RA=$RESETALL;   NA=$RESETALL

### ────────────────────────────────
### BOLD COLORS
### ────────────────────────────────
BOLDBLACK     = "\e[1;30m";  BDBLACK     = $BOLDBLACK;     BDBLK   = $BOLDBLACK
BOLDRED       = "\e[1;31m";  BDRED       = $BOLDRED;       BDRD    = $BOLDRED
BOLDGREEN     = "\e[1;32m";  BDGREEN     = $BOLDGREEN;     BDGRN   = $BOLDGREEN
BOLDYELLOW    = "\e[1;33m";  BDYELLOW    = $BOLDYELLOW;    BDYLW   = $BOLDYELLOW
BOLDBLUE      = "\e[1;34m";  BDBLUE      = $BOLDBLUE;      BDBLU   = $BOLDBLUE
BOLDMAGENTA   = "\e[1;35m";  BDMAGENTA   = $BOLDMAGENTA;   BDMAG   = $BOLDMAGENTA
BOLDCYAN      = "\e[1;36m";  BDCYAN      = $BOLDCYAN;      BDCYN   = $BOLDCYAN
BOLDLGRAY     = "\e[1;37m";  BDLGRAY     = $BOLDLGRAY;     BDLGRY  = $BOLDLGRAY
BOLDGRAY      = "\e[1;90m";  BDGRAY      = $BOLDGRAY;      BDGRY   = $BOLDGRAY
BOLDLRED      = "\e[1;91m";  BDLRED      = $BOLDLRED;      BDLRD   = $BOLDLRED
BOLDLGREEN    = "\e[1;92m";  BDLGREEN    = $BOLDLGREEN;    BDLGRN  = $BOLDLGREEN
BOLDLYELLOW   = "\e[1;93m";  BDLYELLOW   = $BOLDLYELLOW;   BDLYLW  = $BOLDLYELLOW
BOLDLBLUE     = "\e[1;94m";  BDLBLUE     = $BOLDLBLUE;     BDLBLU  = $BOLDLBLUE
BOLDLMAGENTA  = "\e[1;95m";  BDLMAGENTA  = $BOLDLMAGENTA;  BDLMAG  = $BOLDLMAGENTA
BOLDLCYAN     = "\e[1;96m";  BDLCYAN     = $BOLDLCYAN;     BDLCYN  = $BOLDLCYAN
BOLDWHITE     = "\e[1;97m";  BDWHITE     = $BOLDWHITE;     BDWHT   = $BOLDWHITE


### ────────────────────────────────
### FAINT COLORS
### ────────────────────────────────
FAINTBLACK    = "\e[2;30m";  FTBLACK     = $FAINTBLACK;    FTBLK   = $FAINTBLACK
FAINTRED      = "\e[2;31m";  FTRED       = $FAINTRED;      FTRD    = $FAINTRED
FAINTGREEN    = "\e[2;32m";  FTGREEN     = $FAINTGREEN;    FTGRN   = $FAINTGREEN
FAINTYELLOW   = "\e[2;33m";  FTYELLOW    = $FAINTYELLOW;   FTYLW   = $FAINTYELLOW
FAINTBLUE     = "\e[2;34m";  FTBLUE      = $FAINTBLUE;     FTBLU   = $FAINTBLUE
FAINTMAGENTA  = "\e[2;35m";  FTMAGENTA   = $FAINTMAGENTA;  FTMAG   = $FAINTMAGENTA
FAINTCYAN     = "\e[2;36m";  FTCYAN      = $FAINTCYAN;     FTCYN   = $FAINTCYAN
FAINTLGRAY    = "\e[2;37m";  FTLGRAY     = $FAINTLGRAY;    FTLGRY  = $FAINTLGRAY
FAINTGRAY     = "\e[2;90m";  FTGRAY      = $FAINTGRAY;     FTGRY   = $FAINTGRAY
FAINTLRED     = "\e[2;91m";  FTLRED      = $FAINTLRED;     FTLRD   = $FAINTLRED
FAINTLGREEN   = "\e[2;92m";  FTLGREEN    = $FAINTLGREEN;   FTLGRN  = $FAINTLGREEN
FAINTLYELLOW  = "\e[2;93m";  FTLYELLOW   = $FAINTLYELLOW;  FTLYLW  = $FAINTLYELLOW
FAINTLBLUE    = "\e[2;94m";  FTLBLUE     = $FAINTLBLUE;    FTLBLU  = $FAINTLBLUE
FAINTLMAGENTA = "\e[2;95m";  FTLMAGENTA  = $FAINTLMAGENTA; FTLMAG  = $FAINTLMAGENTA
FAINTLCYAN    = "\e[2;96m";  FTLCYAN     = $FAINTLCYAN;    FTLCYN  = $FAINTLCYAN
FAINTWHITE    = "\e[2;97m";  FTWHITE     = $FAINTWHITE;    FTWHT   = $FAINTWHITE


### ────────────────────────────────
### ITALIC COLORS
### ────────────────────────────────
ITALICBLACK   = "\e[3;30m";  ITBLACK     = $ITALICBLACK;   ITBLK   = $ITALICBLACK
ITALICRED     = "\e[3;31m";  ITRED       = $ITALICRED;     ITRD    = $ITALICRED
ITALICGREEN   = "\e[3;32m";  ITGREEN     = $ITALICGREEN;   ITGRN   = $ITALICGREEN
ITALICYELLOW  = "\e[3;33m";  ITYELLOW    = $ITALICYELLOW;  ITYLW   = $ITALICYELLOW
ITALICBLUE    = "\e[3;34m";  ITBLUE      = $ITALICBLUE;    ITBLU   = $ITALICBLUE
ITALICMAGENTA = "\e[3;35m";  ITMAGENTA   = $ITALICMAGENTA; ITMAG   = $ITALICMAGENTA
ITALICCYAN    = "\e[3;36m";  ITCYAN      = $ITALICCYAN;    ITCYN   = $ITALICCYAN
ITALICLGRAY   = "\e[3;37m";  ITLGRAY     = $ITALICLGRAY;   ITLGRY  = $ITALICLGRAY
ITALICGRAY    = "\e[3;90m";  ITGRAY      = $ITALICGRAY;    ITGRY   = $ITALICGRAY
ITALICLRED    = "\e[3;91m";  ITLRED      = $ITALICLRED;    ITLRD   = $ITALICLRED
ITALICLGREEN  = "\e[3;92m";  ITLGREEN    = $ITALICLGREEN;  ITLGRN  = $ITALICLGREEN
ITALICLYELLOW = "\e[3;93m";  ITLYELLOW   = $ITALICLYELLOW; ITLYLW  = $ITALICLYELLOW
ITALICLBLUE   = "\e[3;94m";  ITLBLUE     = $ITALICLBLUE;   ITLBLU  = $ITALICLBLUE
ITALICLMAGENTA= "\e[3;95m";  ITLMAGENTA  = $ITALICLMAGENTA;ITLMAG  = $ITALICLMAGENTA
ITALICLCYAN   = "\e[3;96m";  ITLCYAN     = $ITALICLCYAN;   ITLCYN  = $ITALICLCYAN
ITALICWHITE   = "\e[3;97m";  ITWHITE     = $ITALICWHITE;   ITWHT   = $ITALICWHITE


### ────────────────────────────────
### UNDERLINED COLORS
### ────────────────────────────────
UNDERBLACK    = "\e[4;30m";  ULBLACK     = $UNDERBLACK;    ULBLK   = $UNDERBLACK
UNDERRED      = "\e[4;31m";  ULRED       = $UNDERRED;      ULRD    = $UNDERRED
UNDERGREEN    = "\e[4;32m";  ULGREEN     = $UNDERGREEN;    ULGRN   = $UNDERGREEN
UNDERYELLOW   = "\e[4;33m";  ULYELLOW    = $UNDERYELLOW;   ULYLW   = $UNDERYELLOW
UNDERBLUE     = "\e[4;34m";  ULBLUE      = $UNDERBLUE;     ULBLU   = $UNDERBLUE
UNDERMAGENTA  = "\e[4;35m";  ULMAGENTA   = $UNDERMAGENTA;  ULMAG   = $UNDERMAGENTA
UNDERCYAN     = "\e[4;36m";  ULCYAN      = $UNDERCYAN;     ULCYN   = $UNDERCYAN
UNDERLGRAY    = "\e[4;37m";  ULLGRAY     = $UNDERLGRAY;    ULLGRY  = $UNDERLGRAY
UNDERGRAY     = "\e[4;90m";  ULGRAY      = $UNDERGRAY;     ULGRY   = $UNDERGRAY
UNDERLRED     = "\e[4;91m";  ULLRED      = $UNDERLRED;     ULLRD   = $UNDERLRED
UNDERLGREEN   = "\e[4;92m";  ULLGREEN    = $UNDERLGREEN;   ULLGRN  = $UNDERLGREEN
UNDERLYELLOW  = "\e[4;93m";  ULLYELLOW   = $UNDERLYELLOW;  ULLYLW  = $UNDERLYELLOW
UNDERLBLUE    = "\e[4;94m";  ULLBLUE     = $UNDERLBLUE;    ULLBLU  = $UNDERLBLUE
UNDERLMAGENTA = "\e[4;95m";  ULLMAGENTA  = $UNDERLMAGENTA; ULLMAG  = $UNDERLMAGENTA
UNDERLCYAN    = "\e[4;96m";  ULLCYAN     = $UNDERLCYAN;    ULLCYN  = $UNDERLCYAN
UNDERWHITE    = "\e[4;97m";  ULWHITE     = $UNDERWHITE;    ULWHT   = $UNDERWHITE


### ────────────────────────────────
### BLINKING COLORS
### ────────────────────────────────
BLINKBLACK     = "\e[5;30m";  BLBLACK     = $BLINKBLACK;     BLBLK   = $BLINKBLACK
BLINKRED       = "\e[5;31m";  BLRED       = $BLINKRED;       BLRD    = $BLINKRED
BLINKGREEN     = "\e[5;32m";  BLGREEN     = $BLINKGREEN;     BLGRN   = $BLINKGREEN
BLINKYELLOW    = "\e[5;33m";  BLYELLOW    = $BLINKYELLOW;    BLYLW   = $BLINKYELLOW
BLINKBLUE      = "\e[5;34m";  BLBLUE      = $BLINKBLUE;      BLBLU   = $BLINKBLUE
BLINKMAGENTA   = "\e[5;35m";  BLMAGENTA   = $BLINKMAGENTA;   BLMAG   = $BLINKMAGENTA
BLINKCYAN      = "\e[5;36m";  BLCYAN      = $BLINKCYAN;      BLCYN   = $BLINKCYAN
BLINKLGRAY     = "\e[5;37m";  BLLGRAY     = $BLINKLGRAY;     BLLGRY  = $BLINKLGRAY
BLINKGRAY      = "\e[5;90m";  BLGRAY      = $BLINKGRAY;      BLGRY   = $BLINKGRAY
BLINKLRED      = "\e[5;91m";  BLLRED      = $BLINKLRED;      BLLRD   = $BLINKLRED
BLINKLGREEN    = "\e[5;92m";  BLLGREEN    = $BLINKLGREEN;    BLLGRN  = $BLINKLGREEN
BLINKLYELLOW   = "\e[5;93m";  BLLYELLOW   = $BLINKLYELLOW;   BLLYLW  = $BLINKLYELLOW
BLINKLBLUE     = "\e[5;94m";  BLLBLUE     = $BLINKLBLUE;     BLLBLU  = $BLINKLBLUE
BLINKLMAGENTA  = "\e[5;95m";  BLLMAGENTA  = $BLINKLMAGENTA;  BLLMAG  = $BLINKLMAGENTA
BLINKLCYAN     = "\e[5;96m";  BLLCYAN     = $BLINKLCYAN;     BLLCYN  = $BLINKLCYAN
BLINKWHITE     = "\e[5;97m";  BLWHITE     = $BLINKWHITE;     BLWHT   = $BLINKWHITE


### ────────────────────────────────
### REVERSE VIDEO COLORS
### ────────────────────────────────
REVERSEBLACK     = "\e[7;30m";  RBLACK     = $REVERSEBLACK;     RBLK   = $REVERSEBLACK
REVERSERED       = "\e[7;31m";  RRED       = $REVERSERED;       RRD    = $REVERSERED
REVERSEGREEN     = "\e[7;32m";  RGREEN     = $REVERSEGREEN;     RGRN   = $REVERSEGREEN
REVERSEYELLOW    = "\e[7;33m";  RYELLOW    = $REVERSEYELLOW;    RYLW   = $REVERSEYELLOW
REVERSEBLUE      = "\e[7;34m";  RBLUE      = $REVERSEBLUE;      RBLU   = $REVERSEBLUE
REVERSEMAGENTA   = "\e[7;35m";  RMAGENTA   = $REVERSEMAGENTA;   RMAG   = $REVERSEMAGENTA
REVERSECYAN      = "\e[7;36m";  RCYAN      = $REVERSECYAN;      RCYN   = $REVERSECYAN
REVERSELGRAY     = "\e[7;37m";  RLGRAY     = $REVERSELGRAY;     RLGRY  = $REVERSELGRAY
REVERSEGRAY      = "\e[7;90m";  RGRAY      = $REVERSEGRAY;      RGRY   = $REVERSEGRAY
REVERSELRED      = "\e[7;91m";  RLRED      = $REVERSELRED;      RLRD   = $REVERSELRED
REVERSELGREEN    = "\e[7;92m";  RLGREEN    = $REVERSELGREEN;    RLGRN  = $REVERSELGREEN
REVERSELYELLOW   = "\e[7;93m";  RLYELLOW   = $REVERSELYELLOW;   RLYLW  = $REVERSELYELLOW
REVERSELBLUE     = "\e[7;94m";  RLBLUE     = $REVERSELBLUE;     RLBLU  = $REVERSELBLUE
REVERSELMAGENTA  = "\e[7;95m";  RLMAGENTA  = $REVERSELMAGENTA;  RLMAG  = $REVERSELMAGENTA
REVERSELCYAN     = "\e[7;96m";  RLCYAN     = $REVERSELCYAN;     RLCYN  = $REVERSELCYAN
REVERSEWHITE     = "\e[7;97m";  RWHITE     = $REVERSEWHITE;     RWHT   = $REVERSEWHITE


### ────────────────────────────────
### STRIKETHROUGH COLORS
### ────────────────────────────────
STRIKETHROUGHBLACK     = "\e[9;30m";   STBLACK     = $STRIKETHROUGHBLACK;   STBLK   = $STRIKETHROUGHBLACK
STRIKETHROUGHRED       = "\e[9;31m";   STRED       = $STRIKETHROUGHRED;     STRD    = $STRIKETHROUGHRED
STRIKETHROUGHGREEN     = "\e[9;32m";   STGREEN     = $STRIKETHROUGHGREEN;   STGRN   = $STRIKETHROUGHGREEN
STRIKETHROUGHYELLOW    = "\e[9;33m";   STYELLOW    = $STRIKETHROUGHYELLOW;  STYLW   = $STRIKETHROUGHYELLOW
STRIKETHROUGHBLUE      = "\e[9;34m";   STBLUE      = $STRIKETHROUGHBLUE;    STBLU   = $STRIKETHROUGHBLUE
STRIKETHROUGHMAGENTA   = "\e[9;35m";   STMAGENTA   = $STRIKETHROUGHMAGENTA; STMAG   = $STRIKETHROUGHMAGENTA
STRIKETHROUGHCYAN      = "\e[9;36m";   STCYAN      = $STRIKETHROUGHCYAN;    STCYN   = $STRIKETHROUGHCYAN
STRIKETHROUGHLGRAY     = "\e[9;37m";   STLGRAY     = $STRIKETHROUGHLGRAY;   STLGRY  = $STRIKETHROUGHLGRAY
STRIKETHROUGHGRAY      = "\e[9;90m";   STGRAY      = $STRIKETHROUGHGRAY;    STGRY   = $STRIKETHROUGHGRAY
STRIKETHROUGHLRED      = "\e[9;91m";   STLRED      = $STRIKETHROUGHLRED;    STLRD   = $STRIKETHROUGHLRED
STRIKETHROUGHLGREEN    = "\e[9;92m";   STLGREEN    = $STRIKETHROUGHLGREEN;  STLGN   = $STRIKETHROUGHLGREEN
STRIKETHROUGHLYELLOW   = "\e[9;93m";   STLYELLOW   = $STRIKETHROUGHLYELLOW; STLYLW  = $STRIKETHROUGHLYELLOW
STRIKETHROUGHLBLUE     = "\e[9;94m";   STLBLUE     = $STRIKETHROUGHLBLUE;   STLBU   = $STRIKETHROUGHLBLUE
STRIKETHROUGHLMAGENTA  = "\e[9;95m";   STLMAGENTA  = $STRIKETHROUGHLMAGENTA;STLMAG  = $STRIKETHROUGHLMAGENTA
STRIKETHROUGHLCYAN     = "\e[9;96m";   STLCYAN     = $STRIKETHROUGHLCYAN;   STLCYN  = $STRIKETHROUGHLCYAN
STRIKETHROUGHWHITE     = "\e[9;97m";   STWHITE     = $STRIKETHROUGHWHITE;   STWHT   = $STRIKETHROUGHWHITE


